---
title: "Data  pipelines"
output: html_notebook
---

Data pipelines use the tidyverse style of doing things (ie with pipes!)
```{r}
```


```{r}
library(tidyverse)
```
```{r}
write_csv(iris, "iris.csv")
```

### Read

```{r}
iris_raw = read_csv("iris.csv")


```

##Exploratory analysis
Data explorer package is useful for this analysis
```{r}
DataExplorer::create_report(iris_raw, y = "Species") 
```

##Querying rows ##insert the data in a pipeline

```{r}
iris_raw %>% 
  head(10) ##top raws
tail(10) ## last raws

iris_raw %>% 
  sample_n(10) #random raws selected
iris_raw %>% 
  sample_frac(0.10)

```
Example: where is a specific species

```{r}
iris_raw %>% 
  filter(Species=="setosa", Sepal.Length> 5.5),
        Sepal.Width<3)

```
### Combining in R

Equal
Less / greater than
Not equal
And, or
The return from these is either a TRUE or False

```{r}
TRUE & FALSE
```

```{r}
iris_raw %>% 
  filter_if(is.numeric, ~ . < 5) ##filter to a single column
iris_raw %>% 
  filter_if(is.numeric, all_vars( . <5))


```

```{r}
iris_raw %>% 
  select(-Species, Sepal.Length, Petal.Length)

iris_raw %>% 
  select(Sepal.Length, starts_with("P"), contains("Length")) # Select function using strings or names

iris %>% select_if(is.numeric) ## use select if() to return numeric data from dataset

#Advanced conditions for data selection (select_if()). this is not used for the names  of columns only for their content
##For instance, what if we wanted only numeric columns with a high degree of variation? We use the ~ to say we’re writing a custom condition and then do an AND that checks if the column is numeric and if the number of unique values in the column is more than 30. You tell the statement where the column of data should go by using the place holder symbol (.).

iris %>% select_if(~is.numeric(.) & n_distinct(.) > 30)

is_v_unique_num <- as_mapper(~is.numeric(.) & n_distinct(.) > 30) #If you are going to use the above condition often then use
                                                                 # as_mapper() and create a new function
iris %>% select_if(is_v_unique_num)


```


```{r}
install.packages("ggplot2movies")

library(ggplot2movies)

help(ggplot2movies)

```








